### ISSUE TITLE
Cargo.toml dependencies

### ISSUE THREAD

**Issue by maxwell8888** [linebender/druid-widget-nursery#116]
I am trying out Druid for the first time today. As per the README I have tried using the below in `Cargo.toml` but I am getting the below error.
```toml
[dependencies]
druid = "0.7.0"
druid-widget-nursery = { git = "https://github.com/linebender/druid-widget-nursery" }

[patch.'https://github.com/linebender/druid'.druid]
git = "https://github.com/linebender/druid"
rev = "fc05e965c85fced8720c655685e02478e0530e94"
```
```bash
error: failed to resolve patches for `https://github.com/linebender/druid`

Caused by:
  patch for `druid` in `https://github.com/linebender/druid` points to the same source, but patches must point to different sources
```
I managed to get a demo working using the below, does this do the same thing?
```toml
[dependencies]
druid = { git = "https://github.com/linebender/druid", rev = "fc05e965c85fced8720c655685e02478e0530e94" }
druid-widget-nursery = { git = "https://github.com/linebender/druid-widget-nursery" }
```
